# Generated by Django 3.0.5 on 2020-06-03 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('percentage_similar_hobbies', models.FloatField(default=0)),
                ('percentage_similar_music_types', models.FloatField(default=0)),
                ('percentage_similar_foods', models.FloatField(default=0)),
                ('percentage_similar_books', models.FloatField(default=0)),
                ('percentage_similar_films', models.FloatField(default=0)),
                ('percentage_similar_genres', models.FloatField(default=0)),
                ('percentage_similar_weight', models.FloatField(default=0)),
                ('percentage_similar_growth', models.FloatField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_set', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates_creator_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
