# Generated by Django 3.0.5 on 2020-08-05 17:23

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_search', '0001_initial'),
    ]

    operations = [
        #HStoreExtension(),
        migrations.AddField(
            model_name='candidates',
            name='percentage_similar',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
    ]
