# Generated by Django 3.0.5 on 2020-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='common_percentage',
            field=models.FloatField(default=0),
        ),
    ]
