# Generated by Django 3.0.5 on 2020-05-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='percentage_similar_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='percentage_similar_films',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='percentage_similar_foods',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='percentage_similar_genres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='percentage_similar_growth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='percentage_similar_hobbies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='percentage_similar_music_types',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='percentage_similar_weight',
            field=models.IntegerField(default=0),
        ),
    ]
