# Generated by Django 3.0.5 on 2020-08-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_search', '0002_candidates_percentage_similar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='percentage_similar_books',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='percentage_similar_films',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='percentage_similar_foods',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='percentage_similar_genres',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='percentage_similar_growth',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='percentage_similar_hobbies',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='percentage_similar_music_types',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='percentage_similar_weight',
        ),
    ]
