# Generated by Django 3.0.5 on 2020-05-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_search', '0002_auto_20200531_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='percentage_similar_books',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='percentage_similar_films',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='percentage_similar_foods',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='percentage_similar_genres',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='percentage_similar_growth',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='percentage_similar_hobbies',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='percentage_similar_music_types',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='percentage_similar_weight',
            field=models.FloatField(default=0),
        ),
    ]
