# Generated by Django 3.0.5 on 2020-07-29 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles_settings', '0002_auto_20200728_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Descriptions'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Main?'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='path',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_set', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
