# Generated by Django 3.0.5 on 2020-08-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='description',
        ),
        migrations.RemoveField(
            model_name='films',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='description',
        ),
    ]
