# Generated by Django 3.0.5 on 2020-06-03 12:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('background_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('path', models.ImageField(default='images/default.png', upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('main', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 6, 3, 12, 2, 7, 232025))),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AboutYou',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.IntegerField(choices=[(1, 'Other'), (2, 'Female'), (3, 'Mall')], default=1)),
                ('color_hair', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Other'), (2, 'Brunette'), (3, 'Red'), (4, 'Brown'), (5, 'Anything'), (6, 'Blonde')], max_length=11, null=True, verbose_name='Color of hair')),
                ('color_aye', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Other'), (2, 'Blue'), (3, 'Brown'), (4, 'Gray'), (5, 'Green'), (6, 'Hazel'), (7, 'Amber')], max_length=13, null=True, verbose_name='Color of aye')),
                ('min_age', models.IntegerField(null=True, verbose_name='Minimal age')),
                ('max_age', models.IntegerField(null=True, verbose_name='Maximum age')),
                ('min_growth', models.FloatField(null=True, verbose_name='Minimum growth')),
                ('max_growth', models.FloatField(null=True, verbose_name='Maximum growth')),
                ('min_weight', models.FloatField(null=True, verbose_name='Minimum weight')),
                ('max_weight', models.FloatField(null=True, verbose_name='Maximum weight')),
                ('books', models.ManyToManyField(blank=True, related_name='you_books_set', to='background_data.Books', verbose_name='Favorite books?')),
                ('countries', models.ManyToManyField(related_name='you_countries_set', to='background_data.Countries', verbose_name='Where is this person from?')),
                ('films', models.ManyToManyField(blank=True, related_name='you_films_set', to='background_data.Films', verbose_name='What films?')),
                ('foods', models.ManyToManyField(blank=True, related_name='you_foods_set', to='background_data.Foods', verbose_name='Foods')),
                ('genres', models.ManyToManyField(blank=True, related_name='you_genres_set', to='background_data.Genres', verbose_name='What genres should this person love?')),
                ('hobbies', models.ManyToManyField(blank=True, related_name='you_hobbies_set', to='background_data.Hobbies', verbose_name='Hobbies')),
                ('music_types', models.ManyToManyField(blank=True, related_name='you_music_types_set', to='background_data.MusicType', verbose_name='What music?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.IntegerField(choices=[(1, 'Other'), (2, 'Female'), (3, 'Mall')], default=1)),
                ('color_hair', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Other'), (2, 'Brunette'), (3, 'Red'), (4, 'Brown'), (5, 'Anything'), (6, 'Blonde')], max_length=11, null=True, verbose_name='Color of hair')),
                ('color_aye', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Other'), (2, 'Blue'), (3, 'Brown'), (4, 'Gray'), (5, 'Green'), (6, 'Hazel'), (7, 'Amber')], max_length=13, null=True, verbose_name='Color of aye')),
                ('activate', models.BooleanField(default=False, verbose_name='Activate in search?')),
                ('birthday', models.DateField(null=True, verbose_name='Your birthday')),
                ('name', models.CharField(help_text='100 characters max.', max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('growth', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('books', models.ManyToManyField(blank=True, related_name='my_books_set', to='background_data.Books', verbose_name='Favorite books')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_country_set', to='background_data.Countries', verbose_name='Where are you from?')),
                ('films', models.ManyToManyField(blank=True, related_name='my_films_set', to='background_data.Films', verbose_name='Favorite films')),
                ('foods', models.ManyToManyField(blank=True, related_name='my_foods_set', to='background_data.Foods', verbose_name='Favorite foods')),
                ('genres', models.ManyToManyField(blank=True, related_name='my_genres_set', to='background_data.Genres')),
                ('hobbies', models.ManyToManyField(blank=True, related_name='my_hobbies_set', to='background_data.Hobbies', verbose_name='Favorite hobbies')),
                ('music_types', models.ManyToManyField(blank=True, related_name='my_music_types_set', to='background_data.MusicType', verbose_name='Favorite types of music')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
