# Generated by Django 3.0.5 on 2020-06-03 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 12, 2, 25, 635833)),
        ),
    ]
