# Generated by Django 3.0.5 on 2020-05-24 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0002_aboutme_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 10, 56, 19, 65307, tzinfo=utc)),
        ),
    ]
