# Generated by Django 3.0.5 on 2020-06-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0003_auto_20200603_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutyou',
            name='last_search_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
