# Generated by Django 3.0.5 on 2020-05-31 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0003_gallery_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 31, 20, 14, 40, 954287)),
        ),
    ]
