# Generated by Django 3.0.5 on 2020-06-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0005_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='surname',
        ),
    ]
