# Generated by Django 3.0.5 on 2020-06-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0006_auto_20200622_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
