# Generated by Django 3.0.5 on 2020-07-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_settings', '0007_delete_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
